#!/usr/bin/env python3
"""Synthetic HPO Robustness experiment.

Same experiment as run_hpo_robustness.py, but the graph is generated by the
cSBM model (synth-graph-rs) instead of loaded from a real dataset.

This enables controlled sweeps over:
  --h            : edge homophily (the primary IV)
  --mu           : feature signal strength (confounder check)
  --d            : average degree (confounder check)
  --theta_exp    : Pareto degree-heterogeneity exponent (Texas replication)
  --arch         : GNN architecture (gcn / graphsage / gat)

Output: results/hpo/synth_h{h}_mu{mu}_d{d}_c{c}_n{n}_gs{gs}[_arch_{arch}]_hpo_{metric}.json
        arch suffix omitted for gcn (backward-compatible with existing results).
        Same schema as real-dataset HPO results — NB06/NB07 loader works unchanged.

Usage:
    python scripts/run_synthetic_hpo.py --h 0.1 --mu 1.0 --metric jaccard
    python scripts/run_synthetic_hpo.py --h 0.5 --mu 2.0 --metric random --graph_seed 1
    python scripts/run_synthetic_hpo.py --h 0.1 --mu 1.0 --theta_exp 3.0 --metric approx_er
    python scripts/run_synthetic_hpo.py --h 0.5 --metric jaccard --arch graphsage
    python scripts/run_synthetic_hpo.py --h 0.5 --metric jaccard --use_edge_weights
"""

import argparse
import gc
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from scipy.stats.qmc import LatinHypercube
from torch import nn
from torch_geometric.data import Data
from torch_geometric.nn import GATConv, GCNConv, SAGEConv
from torch_geometric.utils import to_scipy_sparse_matrix

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.sparsification.core import GraphSparsifier
from src.sparsification.metrics import compute_topology_metrics
from src.training.trainer import GNNTrainer

# ── Experiment configuration ──────────────────────────────────────────────────

RETENTION_RATES   = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
N_HP_SAMPLES      = 50
N_SEEDS           = 3
EPOCHS            = 500
PATIENCE          = 50
YIELD_THRESHOLD   = 0.90
RANDOM_SCORE_SEED = 42

# Standard threshold metrics (keep highest-scoring edges)
SPARSIFIER_METRICS = ["jaccard", "adamic_adar", "approx_er", "feature_cosine"]
# Inverse threshold metrics (keep lowest-scoring edges — for heterophilous graphs)
INVERSE_METRICS    = ["jaccard_inv", "adamic_adar_inv", "approx_er_inv", "feature_cosine_inv"]
# Metric backbone — retention ratio determined by graph structure, not a parameter
BACKBONE_METRICS   = ["metric_backbone_jaccard", "metric_backbone_adamic_adar",
                      "metric_backbone_approx_er"]
# Degree-aware threshold: guarantees min edges per node before global threshold
DEGREE_AWARE_METRICS = ["degree_aware_jaccard", "degree_aware_adamic_adar",
                        "degree_aware_approx_er"]
# Probabilistic sampling proportional to edge scores
SAMPLED_METRICS    = ["sampled_jaccard", "sampled_adamic_adar", "sampled_approx_er"]

ALL_METRICS = (SPARSIFIER_METRICS + INVERSE_METRICS + BACKBONE_METRICS
               + DEGREE_AWARE_METRICS + SAMPLED_METRICS + ["random"])

LR_MIN,  LR_MAX  = 1e-4, 1e-1
WD_MIN,  WD_MAX  = 0.0,  5e-2
DO_MIN,  DO_MAX  = 0.0,  0.9
HIDDEN_CHOICES   = [8, 16, 32, 64, 128, 256]
LAYER_CHOICES    = [1, 2, 3, 4]

RESULTS_DIR = REPO_ROOT / "results" / "hpo"


# ── cSBM graph generation ─────────────────────────────────────────────────────

def build_csbm_graph(
    h: float,
    mu: float,
    d: float,
    n: int,
    c: int,
    f: int,
    graph_seed: int,
    theta_exp: float | None,
    device: str,
) -> tuple[Data, float]:
    """Generate a cSBM graph and return (PyG Data, effective_h)."""
    try:
        import synth_graph_rs
    except ImportError:
        raise ImportError(
            "synth-graph-rs is not installed. "
            "Run: cd /path/to/synth-graph-rs && maturin develop --release"
        )

    kwargs = dict(
        n=n, c=c, h=h, d=d, f=f, mu=mu,
        ensure_connected=True,
        seed=graph_seed,
    )
    if theta_exp is not None:
        kwargs["theta_exponent"] = theta_exp

    edge_index_np, x_np, y_np, effective_h = synth_graph_rs.generate_csbm(**kwargs)

    edge_index = torch.from_numpy(edge_index_np).long()
    x          = torch.from_numpy(x_np).float()
    y          = torch.from_numpy(y_np).long()

    train_mask = torch.zeros(n, dtype=torch.bool)
    val_mask   = torch.zeros(n, dtype=torch.bool)
    test_mask  = torch.zeros(n, dtype=torch.bool)

    rng = np.random.default_rng(graph_seed + 1000)
    for cls in range(c):
        idx = np.where(y_np == cls)[0]
        rng.shuffle(idx)
        n_train = min(20, len(idx) // 3)
        n_rest  = len(idx) - n_train
        n_val   = n_rest // 2
        train_mask[idx[:n_train]]                   = True
        val_mask[idx[n_train:n_train + n_val]]      = True
        test_mask[idx[n_train + n_val:]]            = True

    data = Data(x=x, edge_index=edge_index, y=y,
                train_mask=train_mask, val_mask=val_mask, test_mask=test_mask)
    data = data.to(device)
    return data, float(effective_h)


def dataset_name(h: float, mu: float, d: float, c: int, n: int,
                 graph_seed: int, theta_exp: float | None, arch: str) -> str:
    base = f"synth_h{h:.2f}_mu{mu:.2f}_d{d:.1f}_c{c}_n{n}_gs{graph_seed}"
    if theta_exp is not None:
        base += f"_te{theta_exp:.1f}"
    if arch != "gcn":
        base += f"_arch_{arch}"
    return base


# ── Flexible model definitions ────────────────────────────────────────────────

class FlexibleGCN(nn.Module):
    """Variable-depth GCN with configurable hidden size and dropout."""
    def __init__(self, in_channels, hidden_channels, out_channels,
                 num_layers, dropout):
        super().__init__()
        self.dropout = dropout
        self.convs   = nn.ModuleList()
        if num_layers == 1:
            self.convs.append(GCNConv(in_channels, out_channels))
        else:
            self.convs.append(GCNConv(in_channels, hidden_channels))
            for _ in range(num_layers - 2):
                self.convs.append(GCNConv(hidden_channels, hidden_channels))
            self.convs.append(GCNConv(hidden_channels, out_channels))

    def reset_parameters(self):
        for conv in self.convs:
            conv.reset_parameters()

    def forward(self, data, edge_weight=None):
        x, edge_index = data.x, data.edge_index
        for conv in self.convs[:-1]:
            x = conv(x, edge_index, edge_weight=edge_weight)
            x = F.relu(x)
            x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.convs[-1](x, edge_index, edge_weight=edge_weight)
        return F.log_softmax(x, dim=1)


class FlexibleSAGE(nn.Module):
    """Variable-depth GraphSAGE with mean aggregation."""
    def __init__(self, in_channels, hidden_channels, out_channels,
                 num_layers, dropout):
        super().__init__()
        self.dropout = dropout
        self.convs   = nn.ModuleList()
        if num_layers == 1:
            self.convs.append(SAGEConv(in_channels, out_channels))
        else:
            self.convs.append(SAGEConv(in_channels, hidden_channels))
            for _ in range(num_layers - 2):
                self.convs.append(SAGEConv(hidden_channels, hidden_channels))
            self.convs.append(SAGEConv(hidden_channels, out_channels))

    def reset_parameters(self):
        for conv in self.convs:
            conv.reset_parameters()

    def forward(self, data, edge_weight=None):
        # SAGEConv uses mean aggregation; edge_weight is ignored
        x, edge_index = data.x, data.edge_index
        for conv in self.convs[:-1]:
            x = conv(x, edge_index)
            x = F.relu(x)
            x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.convs[-1](x, edge_index)
        return F.log_softmax(x, dim=1)


class FlexibleGAT(nn.Module):
    """Variable-depth GAT with multi-head attention (heads=2 on hidden layers)."""
    def __init__(self, in_channels, hidden_channels, out_channels,
                 num_layers, dropout, heads=2):
        super().__init__()
        self.dropout = dropout
        self.convs   = nn.ModuleList()
        if num_layers == 1:
            self.convs.append(
                GATConv(in_channels, out_channels, heads=1, concat=False, dropout=dropout)
            )
        else:
            self.convs.append(
                GATConv(in_channels, hidden_channels, heads=heads, dropout=dropout)
            )
            for _ in range(num_layers - 2):
                self.convs.append(
                    GATConv(hidden_channels * heads, hidden_channels,
                            heads=heads, dropout=dropout)
                )
            self.convs.append(
                GATConv(hidden_channels * heads, out_channels,
                        heads=1, concat=False, dropout=dropout)
            )

    def reset_parameters(self):
        for conv in self.convs:
            conv.reset_parameters()

    def forward(self, data, edge_weight=None):
        # GAT learns attention internally; edge_weight ignored
        x, edge_index = data.x, data.edge_index
        x = F.dropout(x, p=self.dropout, training=self.training)
        for conv in self.convs[:-1]:
            x = conv(x, edge_index)
            x = F.elu(x)
            x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.convs[-1](x, edge_index)
        return F.log_softmax(x, dim=1)


ARCH_REGISTRY = {
    "gcn":       FlexibleGCN,
    "graphsage": FlexibleSAGE,
    "gat":       FlexibleGAT,
}


# ── Memory profiling ──────────────────────────────────────────────────────────

def _peak_memory_mb(device: str) -> float:
    """Return peak memory usage in MB for the current device."""
    try:
        if device == "cuda":
            mb = torch.cuda.max_memory_allocated() / 1024 ** 2
            torch.cuda.reset_peak_memory_stats()
            return float(mb)
        elif device == "mps":
            return float(torch.mps.current_allocated_memory() / 1024 ** 2)
        else:
            try:
                import psutil
                return float(psutil.Process().memory_info().rss / 1024 ** 2)
            except ImportError:
                return float("nan")
    except Exception:
        return float("nan")


# ── Graph structural metrics ──────────────────────────────────────────────────

def _topology_meta(sparse_data: Data) -> dict:
    """Compute clustering coefficient and algebraic connectivity for a sparse graph."""
    try:
        adj = to_scipy_sparse_matrix(
            sparse_data.edge_index.cpu(), num_nodes=sparse_data.num_nodes
        )
        topo = compute_topology_metrics(adj)
        return {
            "clustering_coeff":       topo.get("clustering_coefficient", float("nan")),
            "algebraic_connectivity": topo.get("algebraic_connectivity",  float("nan")),
            "num_components":         topo.get("num_connected_components", float("nan")),
        }
    except Exception:
        return {
            "clustering_coeff":       float("nan"),
            "algebraic_connectivity": float("nan"),
            "num_components":         float("nan"),
        }


# ── Helper: random sparsification ─────────────────────────────────────────────

def _precompute_random_scores(data):
    ei  = data.edge_index.cpu().numpy()
    src, dst = ei[0], ei[1]
    n   = data.num_nodes
    u   = np.minimum(src, dst)
    v   = np.maximum(src, dst)
    keys = u.astype(np.int64) * (n + 1) + v.astype(np.int64)
    _, inverse_idx    = np.unique(keys, return_inverse=True)
    n_undirected      = int(inverse_idx.max()) + 1
    rng               = np.random.default_rng(RANDOM_SCORE_SEED)
    undirected_scores = rng.random(n_undirected)
    return undirected_scores, inverse_idx


def _random_sparsify(data, undirected_scores, inverse_idx, retention_ratio, device):
    if retention_ratio == 1.0:
        return data.clone()
    n_undirected = len(undirected_scores)
    n_keep       = max(1, int(n_undirected * retention_ratio))
    keep_undir   = np.zeros(n_undirected, dtype=bool)
    keep_undir[np.argsort(undirected_scores)[-n_keep:]] = True
    mask         = keep_undir[inverse_idx]
    sparse       = data.clone()
    sparse.edge_index = data.edge_index[:, mask].to(device)
    return sparse


# ── HP sampling ───────────────────────────────────────────────────────────────

def sample_hp_configs(n: int, seed: int = 42) -> list:
    sampler = LatinHypercube(d=5, seed=seed)
    samples = sampler.random(n=n)
    configs = []
    for u_lr, u_wd, u_do, u_hid, u_lay in samples:
        lr     = 10 ** (np.log10(LR_MIN) + u_lr * (np.log10(LR_MAX) - np.log10(LR_MIN)))
        wd     = WD_MIN + u_wd * (WD_MAX - WD_MIN)
        do     = DO_MIN + u_do * (DO_MAX - DO_MIN)
        hidden = HIDDEN_CHOICES[min(int(u_hid * len(HIDDEN_CHOICES)), len(HIDDEN_CHOICES) - 1)]
        layers = LAYER_CHOICES[min(int(u_lay * len(LAYER_CHOICES)), len(LAYER_CHOICES) - 1)]
        configs.append({
            "lr":              float(round(lr, 7)),
            "weight_decay":    float(round(wd, 6)),
            "dropout":         float(round(do, 4)),
            "hidden_channels": int(hidden),
            "num_layers":      int(layers),
        })
    return configs


# ── Training ──────────────────────────────────────────────────────────────────

def train_one_config(graph, num_features, num_classes, hp, device, seeds,
                     arch: str, edge_weight=None):
    accs, f1s, times, mems = [], [], [], []
    ModelClass = ARCH_REGISTRY[arch]
    for seed in seeds:
        torch.manual_seed(seed)
        np.random.seed(seed)
        model = ModelClass(
            in_channels=num_features,
            hidden_channels=hp["hidden_channels"],
            out_channels=num_classes,
            num_layers=hp["num_layers"],
            dropout=hp["dropout"],
        ).to(device)
        model.reset_parameters()
        optimizer = torch.optim.Adam(
            model.parameters(), lr=hp["lr"], weight_decay=hp["weight_decay"]
        )
        trainer = GNNTrainer(model=model, optimizer=optimizer, device=device)
        t0 = time.time()
        _, history = trainer.train_and_evaluate(
            graph, epochs=EPOCHS, patience=PATIENCE,
            edge_weight=edge_weight,
        )
        accs.append(history["test_metrics"]["accuracy"])
        f1s.append(history["test_metrics"]["macro_f1"])
        times.append(time.time() - t0)
        mems.append(_peak_memory_mb(device))
    return {
        "acc_mean":      float(np.mean(accs)),
        "acc_std":       float(np.std(accs)),
        "f1_mean":       float(np.mean(f1s)),
        "f1_std":        float(np.std(f1s)),
        "train_time_s":  float(np.mean(times)),
        "peak_mem_mb":   float(np.mean(mems)),
    }


# ── Robustness stats ──────────────────────────────────────────────────────────

def compute_robustness_stats(hp_results, best_dense_acc, dense_std):
    accs = np.array([r["acc_mean"] for r in hp_results])
    f1s  = np.array([r["f1_mean"]  for r in hp_results])
    q25, q75    = float(np.percentile(accs, 25)), float(np.percentile(accs, 75))
    best_at_r   = float(accs.max())
    std         = float(np.std(accs))
    rob_gain    = float(dense_std / std) if (dense_std is not None and std > 1e-9) else 1.0
    return {
        "acc_mean":            float(np.mean(accs)),
        "acc_std":             std,
        "acc_iqr":             float(q75 - q25),
        "acc_best":            best_at_r,
        "acc_worst":           float(accs.min()),
        "f1_mean":             float(np.mean(f1s)),
        "f1_std":              float(np.std(f1s)),
        "yield_rate_within":   float((accs >= YIELD_THRESHOLD * best_at_r).mean()),
        "yield_rate_vs_dense": float((accs >= YIELD_THRESHOLD * best_dense_acc).mean()),
        "robustness_gain":     rob_gain,
    }


# ── Checkpoint ────────────────────────────────────────────────────────────────

def _checkpoint(path, ds_name, metric, num_features, num_classes,
                hp_configs, results, synth_meta, arch):
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "meta": {
            "dataset":         ds_name,
            "homophily":       synth_meta["effective_h_dense"],
            "n_hp_configs":    N_HP_SAMPLES,
            "n_seeds":         N_SEEDS,
            "metric":          metric,
            "arch":            arch,
            "retention_rates": RETENTION_RATES,
            "epochs":          EPOCHS,
            "patience":        PATIENCE,
            "yield_threshold": YIELD_THRESHOLD,
            "hp_space": {
                "lr":          [LR_MIN, LR_MAX, "log"],
                "weight_decay":[WD_MIN, WD_MAX, "linear"],
                "dropout":     [DO_MIN, DO_MAX, "linear"],
                "hidden":      HIDDEN_CHOICES,
                "num_layers":  LAYER_CHOICES,
            },
            "num_features":    num_features,
            "num_classes":     num_classes,
            "synth": synth_meta,
        },
        "hp_configs": hp_configs,
        "results":    results,
    }
    with open(path, "w") as f:
        json.dump(payload, f, indent=2)


# ── Sparsification dispatch ───────────────────────────────────────────────────

def _parse_composite_metric(metric: str) -> tuple[str, str]:
    """Return (strategy, base_metric) for composite metric names.

    E.g. 'degree_aware_jaccard' → ('degree_aware', 'jaccard')
         'metric_backbone_approx_er' → ('metric_backbone', 'approx_er')
         'sampled_adamic_adar' → ('sampled', 'adamic_adar')
         'jaccard' → ('threshold', 'jaccard')
         'jaccard_inv' → ('inverse', 'jaccard')
         'random' → ('random', 'random')
    """
    for prefix in ("metric_backbone_", "degree_aware_", "sampled_"):
        if metric.startswith(prefix):
            return prefix.rstrip("_"), metric[len(prefix):]
    if metric.endswith("_inv"):
        return "inverse", metric[:-4]
    if metric == "random":
        return "random", "random"
    return "threshold", metric


def _build_sparsify_fn(metric: str, data: Data, device: str,
                       use_edge_weights: bool):
    """Return (preprocess_time_s, _sparsify_fn, edge_scores_or_None, is_backbone).

    For backbone metrics the returned fn ignores `r` and always returns the
    backbone graph.  Callers should detect `is_backbone=True` and skip the
    standard retention-rate loop, running the backbone separately.
    """
    strategy, base = _parse_composite_metric(metric)

    t0 = time.time()
    if strategy == "random":
        undirected_scores, inverse_idx = _precompute_random_scores(data)
        preprocess_time = time.time() - t0
        scores_for_weights = None

        def _sparsify(r):
            return _random_sparsify(data, undirected_scores, inverse_idx, r, device)

        return preprocess_time, _sparsify, scores_for_weights, False

    # All non-random strategies use GraphSparsifier
    sparsifier = GraphSparsifier(data, device)
    sparsifier.compute_scores(base)
    preprocess_time = time.time() - t0

    # Edge scores for edge_weight (GCN only, when --use_edge_weights)
    scores_for_weights = None
    if use_edge_weights:
        raw = sparsifier.scores.get(base)
        if raw is not None:
            scores_for_weights = torch.tensor(raw, dtype=torch.float, device=device)

    if strategy == "threshold":
        def _sparsify(r):
            return sparsifier.sparsify(base, r)
    elif strategy == "inverse":
        def _sparsify(r):
            return sparsifier.sparsify(base, r, keep_lowest=True)
    elif strategy == "degree_aware":
        def _sparsify(r):
            return sparsifier.sparsify_degree_aware(base, r)
    elif strategy == "sampled":
        def _sparsify(r):
            return sparsifier.sparsify_sampled(base, r)
    elif strategy == "metric_backbone":
        # Backbone ignores r — will be handled separately after the main loop
        def _sparsify(r):
            sparse_data, _ = sparsifier.sparsify_metric_backbone(base)
            return sparse_data
        return preprocess_time, _sparsify, scores_for_weights, True
    else:
        raise ValueError(f"Unknown strategy: {strategy}")

    return preprocess_time, _sparsify, scores_for_weights, False


# ── Main experiment loop ──────────────────────────────────────────────────────

def run_synthetic(
    h: float, mu: float, d: float, n: int, c: int, f: int,
    graph_seed: int, theta_exp: float | None,
    device: str, resume: bool, metric: str,
    arch: str, use_edge_weights: bool,
) -> None:
    ds_name     = dataset_name(h, mu, d, c, n, graph_seed, theta_exp, arch)
    output_path = RESULTS_DIR / f"{ds_name}_hpo_{metric}.json"

    existing_results = {}
    completed_keys   = set()
    if resume and output_path.exists():
        with open(output_path) as fh:
            existing = json.load(fh)
        existing_results = existing.get("results", {})
        completed_keys   = set(existing_results.keys())
        print(f"  Resuming — {len(completed_keys)} keys done: "
              f"{sorted(completed_keys, key=lambda x: (x != 'backbone', float(x) if x != 'backbone' else 0))}")

    print(f"\n{'#'*70}")
    print(f"# SYNTHETIC: {ds_name}  |  Metric: {metric}  |  Arch: {arch}  |  Device: {device}")
    print(f"{'#'*70}")

    print(f"  Generating cSBM graph: h={h}, mu={mu}, d={d}, n={n}, c={c}, "
          f"f={f}, graph_seed={graph_seed}, theta_exp={theta_exp}")
    data, effective_h = build_csbm_graph(h, mu, d, n, c, f, graph_seed, theta_exp, device)
    num_features = f
    num_classes  = c

    print(f"  {data.num_nodes:,} nodes  {data.edge_index.size(1):,} edges  "
          f"requested_h={h:.3f}  effective_h={effective_h:.3f}")

    synth_meta = {
        "requested_h":       h,
        "effective_h_dense": effective_h,
        "mu":                mu,
        "d":                 d,
        "n":                 n,
        "c":                 c,
        "f":                 f,
        "graph_seed":        graph_seed,
        "theta_exponent":    theta_exp,
        "arch":              arch,
    }

    hp_configs = sample_hp_configs(N_HP_SAMPLES, seed=42)
    print(f"  Sampled {N_HP_SAMPLES} HP configs (LHC, seed=42)")

    print(f"  Building sparsifier for metric={metric}...")
    preprocess_time, _sparsify, edge_scores, is_backbone = _build_sparsify_fn(
        metric, data, device, use_edge_weights
    )
    print(f"  Preprocessing done in {preprocess_time:.1f}s")

    results   = existing_results.copy()
    seeds     = list(range(N_SEEDS))
    dense_std = None

    if "1.0" in results:
        dense_std = results["1.0"]["robustness_stats"]["acc_std"]

    # ── Standard retention-rate loop ──────────────────────────────────────────
    # For backbone metrics: only run r=1.0 (dense baseline); backbone handled below
    rates_to_run = [1.0] if is_backbone else RETENTION_RATES

    for r in sorted(rates_to_run, reverse=True):
        r_key = str(r)

        if r_key in completed_keys:
            print(f"  r={r:.1f}  SKIPPED (already done)")
            if r == 1.0 and dense_std is None:
                dense_std = results[r_key]["robustness_stats"]["acc_std"]
            continue

        sparse_data = _sparsify(r)
        n_edges     = int(sparse_data.edge_index.size(1))

        s_src = sparse_data.edge_index[0].cpu()
        s_dst = sparse_data.edge_index[1].cpu()
        y_cpu = data.y.cpu()
        sparse_effective_h = float((y_cpu[s_src] == y_cpu[s_dst]).float().mean().item())

        # Edge weights for this retention ratio (threshold on scores, GCN only)
        ew = None
        if use_edge_weights and edge_scores is not None and arch == "gcn":
            # Build a mask matching the sparsified edge_index
            full_ei   = data.edge_index.cpu()
            sparse_ei = sparse_data.edge_index.cpu()
            full_set  = {(int(full_ei[0, i]), int(full_ei[1, i])): i
                         for i in range(full_ei.size(1))}
            idx       = [full_set[(int(sparse_ei[0, j]), int(sparse_ei[1, j]))]
                         for j in range(sparse_ei.size(1))
                         if (int(sparse_ei[0, j]), int(sparse_ei[1, j])) in full_set]
            ew = edge_scores[idx] if idx else None

        topo = _topology_meta(sparse_data)

        print(f"\n  r={r:.1f}  ({n_edges:,} edges, eff_h={sparse_effective_h:.3f})  —  "
              f"{N_HP_SAMPLES} configs × {N_SEEDS} seeds")

        hp_results = []
        t_start    = time.time()
        for i, hp in enumerate(hp_configs):
            try:
                res = train_one_config(
                    sparse_data, num_features, num_classes, hp, device, seeds,
                    arch=arch, edge_weight=ew,
                )
            except Exception as e:
                print(f"    [SKIP hp_idx={i}] {type(e).__name__}: {e}")
                continue
            hp_results.append({"hp_idx": i, **res})

            if (i + 1) % 10 == 0:
                mean_so_far = np.mean([x["acc_mean"] for x in hp_results])
                elapsed     = (time.time() - t_start) / 60
                print(f"    [{i+1:3d}/{N_HP_SAMPLES}]  "
                      f"running mean acc={mean_so_far:.4f}  "
                      f"elapsed={elapsed:.1f}m")

        best_dense_acc = (
            float(max(x["acc_mean"] for x in hp_results))
            if r == 1.0
            else float(results["1.0"]["meta"]["best_dense_acc"])
        )

        stats = compute_robustness_stats(hp_results, best_dense_acc, dense_std)
        if r == 1.0:
            dense_std = stats["acc_std"]

        results[r_key] = {
            "meta": {
                "retention_ratio":  r,
                "n_edges":          n_edges,
                "best_dense_acc":   best_dense_acc,
                "effective_h":      sparse_effective_h,
                "preprocess_time_s": preprocess_time,
                **topo,
            },
            "hp_results":       hp_results,
            "robustness_stats": stats,
        }

        _checkpoint(output_path, ds_name, metric, num_features, num_classes,
                    hp_configs, results, synth_meta, arch)

        print(f"  r={r:.1f}  DONE  "
              f"std={stats['acc_std']:.4f}  "
              f"yield_within={stats['yield_rate_within']:.1%}  "
              f"gain={stats['robustness_gain']:.2f}x  "
              f"f1={stats['f1_mean']:.4f}  "
              f"[{(time.time()-t_start)/60:.1f}m]")

    # ── Backbone: run once after the loop ─────────────────────────────────────
    if is_backbone and "backbone" not in completed_keys:
        print(f"\n  Running metric backbone (r determined by graph structure)...")
        if dense_std is None and "1.0" in results:
            dense_std = results["1.0"]["robustness_stats"]["acc_std"]

        backbone_data = _sparsify(1.0)  # backbone fn ignores r
        n_edges       = int(backbone_data.edge_index.size(1))
        actual_r      = n_edges / int(data.edge_index.size(1))

        s_src = backbone_data.edge_index[0].cpu()
        s_dst = backbone_data.edge_index[1].cpu()
        y_cpu = data.y.cpu()
        backbone_eff_h = float((y_cpu[s_src] == y_cpu[s_dst]).float().mean().item())
        topo           = _topology_meta(backbone_data)

        best_dense_acc = float(results["1.0"]["meta"]["best_dense_acc"]) if "1.0" in results else 0.0

        print(f"  backbone  ({n_edges:,} edges, actual_r={actual_r:.3f}, "
              f"eff_h={backbone_eff_h:.3f})  —  {N_HP_SAMPLES} configs × {N_SEEDS} seeds")

        hp_results = []
        t_start    = time.time()
        for i, hp in enumerate(hp_configs):
            try:
                res = train_one_config(
                    backbone_data, num_features, num_classes, hp, device, seeds,
                    arch=arch,
                )
            except Exception as e:
                print(f"    [SKIP hp_idx={i}] {type(e).__name__}: {e}")
                continue
            hp_results.append({"hp_idx": i, **res})

            if (i + 1) % 10 == 0:
                elapsed = (time.time() - t_start) / 60
                print(f"    [{i+1:3d}/{N_HP_SAMPLES}]  "
                      f"running mean acc={np.mean([x['acc_mean'] for x in hp_results]):.4f}  "
                      f"elapsed={elapsed:.1f}m")

        stats = compute_robustness_stats(hp_results, best_dense_acc, dense_std)

        results["backbone"] = {
            "meta": {
                "retention_ratio":   actual_r,
                "n_edges":           n_edges,
                "best_dense_acc":    best_dense_acc,
                "effective_h":       backbone_eff_h,
                "preprocess_time_s": preprocess_time,
                **topo,
            },
            "hp_results":       hp_results,
            "robustness_stats": stats,
        }

        _checkpoint(output_path, ds_name, metric, num_features, num_classes,
                    hp_configs, results, synth_meta, arch)

        print(f"  backbone  DONE  "
              f"actual_r={actual_r:.3f}  "
              f"std={stats['acc_std']:.4f}  "
              f"yield_within={stats['yield_rate_within']:.1%}  "
              f"gain={stats['robustness_gain']:.2f}x  "
              f"[{(time.time()-t_start)/60:.1f}m]")

    print(f"\n  Saved → {output_path}")
    del data
    gc.collect()
    if device == "cuda":
        torch.cuda.empty_cache()


# ── CLI ───────────────────────────────────────────────────────────────────────

def get_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Synthetic HPO Robustness: sweep cSBM parameters to isolate "
                    "the causal driver of HP landscape ruggedness."
    )
    parser.add_argument("--h",          type=float, required=True,
                        help="Requested edge homophily ratio [0, 1]")
    parser.add_argument("--mu",         type=float, default=1.0,
                        help="Feature signal strength (default: 1.0)")
    parser.add_argument("--d",          type=float, default=10.0,
                        help="Average degree (default: 10.0)")
    parser.add_argument("--n",          type=int,   default=1000,
                        help="Number of nodes (default: 1000)")
    parser.add_argument("--c",          type=int,   default=5,
                        help="Number of communities/classes (default: 5)")
    parser.add_argument("--f",          type=int,   default=512,
                        help="Feature dimensionality (default: 512)")
    parser.add_argument("--graph_seed", type=int,   default=0,
                        help="RNG seed for graph generation (default: 0)")
    parser.add_argument("--theta_exp",  type=float, default=None,
                        help="Pareto exponent for degree heterogeneity (default: None = uniform)")
    parser.add_argument("--metric",     type=str,   default="jaccard",
                        choices=ALL_METRICS,
                        help="Sparsification metric/strategy")
    parser.add_argument("--arch",       type=str,   default="gcn",
                        choices=list(ARCH_REGISTRY.keys()),
                        help="GNN architecture (default: gcn)")
    parser.add_argument("--use_edge_weights", action="store_true",
                        help="Pass sparsification scores as edge weights (GCN only)")
    parser.add_argument("--resume",     action="store_true")
    args = parser.parse_args()

    if args.use_edge_weights and args.arch != "gcn":
        parser.error("--use_edge_weights is only supported for --arch gcn")

    device = get_device()
    print(f"Device: {device}  |  Metric: {args.metric}  |  Arch: {args.arch}")
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    t0 = time.time()
    run_synthetic(
        h=args.h, mu=args.mu, d=args.d, n=args.n, c=args.c, f=args.f,
        graph_seed=args.graph_seed, theta_exp=args.theta_exp,
        device=device, resume=args.resume, metric=args.metric,
        arch=args.arch, use_edge_weights=args.use_edge_weights,
    )
    print(f"\nCompleted in {(time.time()-t0)/60:.1f} minutes")


if __name__ == "__main__":
    main()
